plugins {
    id("gg.essential.multi-version.root")
}

preprocess {
    def bukkit12111 = createNode("1.21.11", 12111, "mojmap") // Added
    def bukkit12110 = createNode("1.21.10", 12110, "mojmap") 
    def bukkit12108 = createNode("1.21.8", 12108, "mojmap")
    def bukkit12105 = createNode("1.21.5", 12105, "mojmap")
    def bukkit12104 = createNode("1.21.4", 12104, "mojmap")
    def bukkit12101 = createNode("1.21.1", 12101, "mojmap")
    def bukkit12001 = createNode("1.20.1", 12001, "mojmap")

    strictExtraMappings.set(true)
    bukkit12110.link(bukkit12111, null)  // CHANGED - now links to 1.21.11
    bukkit12108.link(bukkit12111, null)  
    bukkit12105.link(bukkit12111, null)  
    bukkit12104.link(bukkit12111, null)  
    bukkit12101.link(bukkit12111, null)  
    bukkit12001.link(bukkit12111, null)  
}